version: '3.8'

services:
  db:
    container_name: notes_service_db
    image: 'postgres'
    env_file:
      - dev.env 
    ports:
      - 5432:5432 
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

  server:
    container_name: notes_service_back
    build:
      context: ../../
      dockerfile: ./zarf/docker/UnusualDockerfile
    env_file:
      - dev.env
    ports:
      - 8080:8080
    restart: on-failure
    depends_on: 
      - db

volumes:
  db: