apiVersion: apps/v1
kind: Deployment

metadata:
  name: web
  labels:
    app: web

spec:
  selector:
    matchLabels:
      app: web

  replicas: 2

  template:
    metadata:
      name: web
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: valeriya/web-server
